server:
  port: 9981
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jm_voucher?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: jm_voucher
    password: voucher2019
    druid:
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: jumeng
        # 登录密码
        login-password: jumeng2019
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 6379
    password: jumeng2019
    database: 0
swagger2:
  enable: true