server:
  use-forward-headers: true
  tomcat:
    remote-ip-header: X-Real-IP
    port-header: X-Forwarded-Proto
spring:
  profiles:
    active: dev
  devtools:
    livereload:
      port: 35731
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  jpa:
    open-in-view: false
    database: mysql
  redis:
    timeout: 1000
    lettuce:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 10
        min-idle: 0
  thymeleaf:
    cache: true
    check-template-location: false
    enabled: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
jwt:
  secret: jumengsoftSECRET123456789
  #token 两个小时过期
  expiration: 7200000
  #refreshToken 四个小时过期
  refreshExpiration: 14200000
  token: Authorization
  startStr: Bearer
setting:
  #登录多次失败是否锁定
  isLoginFailureLock: true
  #登录失败次数
  loginFailureLockTime: 5